<a href="https://colab.research.google.com/github/Samia1743/Basic/blob/master/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Write a NumPy code block to create an array with the values 105, 150, 120, 900.


In [ ]:
import numpy as np
a=np.array([105, 150, 120, 900])
a

array([105, 150, 120, 900])

## 2. Write a NumPy  code block to create an array of the integers from 152 to 62.



In [ ]:
import numpy as np
import math
a = np.arange(152,61,-1)
a

array([152, 151, 150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140,
       139, 138, 137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127,
       126, 125, 124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114,
       113, 112, 111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101,
       100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62])

## 3. Write a NumPy  code block to generate a random number between 0 and 100.


In [ ]:
import numpy as np
e = np.random.normal((0,100)) 
print(e)

[-1.98781326 97.67193493]


## 4. Write a NumPy  code block to create a vector of length 1000 with values evenly distributed between 5 and 500.


In [ ]:
import numpy as np
v = np.linspace(5,500,1000)
v

array([  5.        ,   5.4954955 ,   5.99099099,   6.48648649,
         6.98198198,   7.47747748,   7.97297297,   8.46846847,
         8.96396396,   9.45945946,   9.95495495,  10.45045045,
        10.94594595,  11.44144144,  11.93693694,  12.43243243,
        12.92792793,  13.42342342,  13.91891892,  14.41441441,
        14.90990991,  15.40540541,  15.9009009 ,  16.3963964 ,
        16.89189189,  17.38738739,  17.88288288,  18.37837838,
        18.87387387,  19.36936937,  19.86486486,  20.36036036,
        20.85585586,  21.35135135,  21.84684685,  22.34234234,
        22.83783784,  23.33333333,  23.82882883,  24.32432432,
        24.81981982,  25.31531532,  25.81081081,  26.30630631,
        26.8018018 ,  27.2972973 ,  27.79279279,  28.28828829,
        28.78378378,  29.27927928,  29.77477477,  30.27027027,
        30.76576577,  31.26126126,  31.75675676,  32.25225225,
        32.74774775,  33.24324324,  33.73873874,  34.23423423,
        34.72972973,  35.22522523,  35.72072072,  36.21

## 5.  Write a NumPy  code block to create a 4x3 matrix filled with values from 10 to 21.


In [ ]:
import numpy as np
x=np.array([[10,11,12],[13,14,15],[16,17,18],[19,20,21]])
x

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])